#!/usr/bin/env bash

# SPDX-License-Identifier: MIT

# Copyright 2023 Chindraba (Ronald Lamoreaux) <DishUSBImager@chindraba.work>

# Configuration file for DishUSBimager script

# name: archive_dir
# type: string
# value: local filesystem path for STB image archives and working directory
# - May be absolute or relative, though absolute is prefered for operability
# - Defaults to the '/var/opt/DishUSBimage/archives' if it exists, otherwise
# - to the 'archives' subdirectory in the script's true path
# archive_dir=''

# name: archive_handle
# type: string
# value: the file name for downloading STB image archive, exclusive of file extension
# - Usually a generic name redirected by the server
# archive_handle='STBimage'
# archive_handle=''

# name: archive_type
# type: string
# value: the standard extension for the format of downloaded archives
# archive_type='zip'
# archive_type=''

# name: archive_repo
# type: string
# value: URL of Dish network's repository of STB image archives
# archive_repo='https://dns.dish.com/img_repo'
# archive_repo=''
