#!/usr/bin/env bash

# SPDX-License-Identifier: MIT

# Copyright 2023 Chindraba (Ronald Lamoreaux) <dishusbimager@chindraba.work>

_messageOut() { printf "%s\n" "${@}"; }

usage() {
    _messageOut 'At least one argument must be provided.' >&2
}

# Check for parameters, minimum of one required
if [[ 0 -eq $# ]];
then
    ! usage >&2;
    exit 1;
fi

_messageOut 'At least one argument found.'
# vim: syntax=bash ts=4 sw=4 sts=4 et sr
